###read all users(request to protected route)

GET http://localhost:4000/user-api/users

### read a user by id
###
GET http://localhost:4000/user-api/user

###create a user
###
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"ravi",
    "password":"ravi",
    "email":"ravi@gmail.com",
    "age":20
}   



###
###update user
PUT http://localhost:4000/user-api/users/69aa8c3ec0be058d77432708
Content-Type: application/json

{
    "username":"ravi",
    "password":"rav1@123",
    "email":"ravi@gmail.com",
    "age":20
}


###user login
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "email":"ravi@gmail.com",
    "password":"ravi"
}

###
DELETE http://localhost:4000/user-api/users/69aa81ca71376e7922260c5e
### passing id,name,age through end points


###add product to the user cart
PUT http://localhost:4000/user-api/cart/product-id/69b2519afe02e7b16560ea44




###
GET http://localhost:4000/product-api/products

###read user by id
###
GET http://localhost:4000/product-api/products/

###added a product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productId":"b123",
    "productName":"macBook",
    "price":45000,
    "brand":"mac"
}


###update the existing product
###
PUT http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productId":2,
    "ProductName":"Laptop",
    "price":150000,
    "brand":"mac"
}

###delete a product
###
DELETE http://localhost:4000/product-api/products/1